# Generated by Django 4.1.7 on 2023-02-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gallery')),
            ],
        ),
    ]
