# Generated by Django 4.1.7 on 2023-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('sectiontitle', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
                ('paragraph3', models.TextField(blank=True, null=True)),
                ('paragraph4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='img3',
        ),
    ]
