# Generated by Django 4.1.7 on 2023-02-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanamout', models.PositiveIntegerField()),
                ('loanterm', models.PositiveIntegerField()),
                ('intrestrate', models.PositiveIntegerField()),
                ('monthlyemi', models.PositiveIntegerField()),
                ('intrestamount', models.PositiveIntegerField()),
                ('totalamount', models.PositiveIntegerField()),
            ],
        ),
    ]
