# Generated by Django 4.1.7 on 2023-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_phone_alter_emi_intrestamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
