# Generated by Django 4.1.7 on 2023-03-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_photo_options_remove_photo_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
