# Generated by Django 4.1.7 on 2023-03-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_galleryimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
